### ISSUE TITLE
A Guessing Game

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#13]
_This is assignment 13 and is due on Feb 02, 2015._

* Create a guessing game
* The user must guess the number chosen by the app
* Provide feedback to the user as to if their guess is lower or higher than the number
* Count the number of guesses and output at the end

**Comment by tgaeta** [comment]
@brianburridge https://github.com/tgaeta/Assignments/blob/master/assignment13.rb

**Comment by brianburridge** [comment]
Hi @tgaeta 

This works, but your use of the word `exit` in the loop, aborts the entire app. So, if you had any other code to run after the loop, it wouldn't work. In this case, you want to use `break` to just break out of the loop.

**Comment by tgaeta** [comment]
@brianburridge Thanks. I'll change it and push it back up. :)
