### ISSUE TITLE
Classy Pig Latin

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#14]
_This is assignment 14 and is due on Feb 02, 2015._

* Using the structure of a class as I've laid out in this [gist](https://gist.github.com/brianburridge/7e98d358dee03c6b6060), finishing creating the PigLatin class to translate a word into pig latin
* Bonus: modify the app to convert an entire phrase (one word at a time)
* Note the pig latin rules in the comment of the skeleton app

**Comment by tgaeta** [comment]
@brianburridge https://github.com/tgaeta/Assignments/blob/master/assignment14.rb

**Comment by brianburridge** [comment]
On line 12 you have:

        puts "#{passed_text}" + "way"

However, that's not the reason we use string interpolation. We use it to combine variables or Ruby code with Strings. For example:

        puts "#{passed_text} way"

Or:

        puts passed_text + " way"

Either of those would be better options.

**Comment by brianburridge** [comment]
This isn't working quite right. Clean up the usages of String interpolation to make it easier to use. But also, in the end, the pigatized text should be printed (from line 35) and it is currently not.

**Comment by tgaeta** [comment]
@brianburridge Okay.. I'll take another swing at it. Thanks.

**Comment by brianburridge** [comment]
@tgaeta Words starting with vowels aren't translating into piglatin properly. Also, be sure to handle both upper and lower cases.

**Comment by brianburridge** [comment]
:+1:
