### ISSUE TITLE
Movie Querying script

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#18]
_This is assignment 18 and is due on Feb 04, 2015._

* http://developer.rottentomatoes.com/
* Use Rotten Tomato's movie querying script to create a command line app which prompts the user for a movie title
* Using the entered movie title, search via the API for the movie's synopsis and output to the user
* If more than one movie comes back, show all the movie title matches with their synopsis

**Comment by tgaeta** [comment]
@brianburridge 
https://github.com/tgaeta/Assignments/blob/master/assignment18.rb

**Comment by brianburridge** [comment]
This works good. I don't quite understand this line though:

        shutdown = 'this is the end'.downcase.gsub(' ', '%20')

I'd like to hear about it, but nonetheless, I'm closing this because it is working. :smile:

**Comment by tgaeta** [comment]
@brianburridge It a [comedy](http://www.imdb.com/title/tt1245492/) about the end of the world. Kind of an easter egg to end the program.

**Comment by brianburridge** [comment]
Ok. :) It was the gsub part that threw me off. I see what you were trying to do. I would probably not have done gsub on either the shutdown variable nor the move title input, but instead done the gsub  on line 17. That way you preserve the user's movie title input. For example, if you needed to output their search query. At present if you output it, it would look confusing to the user.

**Comment by tgaeta** [comment]
@brianburridge I see what you're saying. Fixed.
