### ISSUE TITLE
Extending String with PigLatin

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#20]
_This is assignment 19 and is due on Feb 04, 2015._

Extend Ruby's String class to have a "pigatize" method that will turn any string into pig latin.

Should use the same code you wrote before, but now you are extending the String class and putting the functionality in there.

**Comment by tgaeta** [comment]
@brianburridge 
https://github.com/tgaeta/Assignments/blob/master/assignment19.rb

The big thing that tripped me up all day/night was trying to replicate what you went over this morning in irb... which wasn't even needed to do this assignment (e.g.:  def something_something! and the word 'replace' had me running in circles for hours). [Screenshot of Morning Example](http://i.imgur.com/BhHmPdP.png)

I interpreted what you went over this morning as the way to extend the Ruby String class with a method.

**Comment by brianburridge** [comment]
The example showed two methods being added to the String class. You would need the `replace` if you were going to add a `pigatize!` method that _replaced_ the string it's being called on.

:+1:
