### ISSUE TITLE
Attributes, accessors, instance variables and private methods

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#21]
_This is assignment 21 and is due on Feb 05, 2015._

* Write a Person class and some code to use it, following the directions below.

## First

* Create a Person class with attributes: first name, last name, and birthdate.
* First name and last name should not be able to be written to, but should be readable.
* Birthdate can be set and read.
* Create a public instance method called `name` that takes the name and sets the first name and last name instance variables. This is so the first name and last name attributes are set by passing in one name.
* Create a public instance method called `age` to calculate and return the user's age.
* Now, outside the Person class, ask the user their information and use it to create the Person object.
* After asking each user their information, output the user's age.

## Next

* Create a class variable that will count the number of people that enter in their information. After you output the person's age, also output the number of person they are so far (using the class variable).
* Loop to allow another user to enter their information. (exit when user enters \q for name). Create a Person object for each user.
* Create a private method called `calculateAge`. This should contain the functionality you previously had in the `age` method. The public `age` method should now call this new private `calculateAge` method.

**Comment by tgaeta** [comment]
@brianburridge 
https://github.com/tgaeta/Assignments/blob/master/assignment21.rb

**Comment by brianburridge** [comment]
Hey @tgaeta 

A few things on this one to clean up:
1. You don't want age to be a reader because you need an age method to call the private calculateAge method (see requirement above).
2. The `name` method should be setup like a setter: `name=`
3. The `bd` method isn't necessary. The birthdate the user enters should go right into the birthdate attribute.
4. The `findage` method isn't necessary. See the first point.
5. In the calculate method you don't need to do any of the `strftime`. That is for formatting from a Date to a String. I'm going to talk about calculating the age tomorrow.

**Comment by tgaeta** [comment]
@brianburridge 

Made the changes you requested. Figured out an easier way to do the age calculation.

**Comment by brianburridge** [comment]
One more thing. Separate out the person class from the assignment code.

**Comment by tgaeta** [comment]
@brianburridge 
Now inside a folder:
https://github.com/tgaeta/Assignments/tree/master/assignment21

**Comment by brianburridge** [comment]
:exclamation:
