### ISSUE TITLE
More work with classes, getters and setters (in class, pairing)

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#26]
_This is assignment 25b and is due on Feb 10, 2015._

* Design and code a Blog and Post class.
* These classes should model a system where a user can create a blog, which will have posts.
* A Blog can have a name, a user_name, and the collection of posts
* A Post can have a name, a summary, the body of the post, the published date, and a word count.
* Since both a blog and a post MUST have a name, override the initializer so that when an object of either class is created, a name must be supplied.

**Comment by tgaeta** [comment]
@brianburridge https://github.com/tgaeta/Assignments/tree/master/assignment25b

**Comment by tgaeta** [comment]
@brianburridge fixed the date published - added comments

**Comment by brianburridge** [comment]
A few tips here:

1. Don't forget it's safer to use CGI::escape instead of gsub to handle spaces in text from the user for use in a URL, because it covers so much more than just spaces.
2. On line 37 of main.rb, you could have used a select instead of iterating over them all with an each.
3. For the Invoice.each_invoice, same comment I made on the other assignment. The method name is confusing. Looks like it's some kind of custom iterator, but really you are just displaying the invoice.

:+1:

**Comment by brianburridge** [comment]
Reopened. Had closed by mistake. Talked to you in person about the 5th requirement (the initializers).

**Comment by tgaeta** [comment]
@brianburridge https://github.com/tgaeta/Assignments/tree/master/assignment25b

**Comment by brianburridge** [comment]
:+1:
