### ISSUE TITLE
Walmart API for Invoices (Bonus)

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#27]
_This is assignment 26 and is due on Feb 11, 2015._

* This is a bonus assignment for those who are caught up on your past homework and are able to finish the HTML/CSS assignment quickly.
* Take what we did in class with the Walmart API, and combine it with what you created in assignment 23
* Prompt the user to search for a product and allow the user to enter the product id (from the search results). For the product indicated, create an InvoiceItem object and add it to your Invoice object
* After the user adds a product to the invoice (using your InvoiceItem class), loop and allow them to search again
* When the user hits ENTER instead of a SEARCH term or a product id, print out the same result as in Assignment 23.
* Bonus to the Bonus: add a category attribute to your InvoiceItem and set it from the Walmart API. Include the category on the output invoice.

**Comment by tgaeta** [comment]
@brianburridge https://github.com/tgaeta/Assignments/tree/master/assignment26

Also attempted the bonus to the bonus. Now off to bed. :)

**Comment by brianburridge** [comment]
A few tips here:

1. Don't forget it's safer to use CGI::escape instead of gsub to handle spaces in text from the user for use in a URL, because it covers so much more than just spaces.
2. On line 37 of main.rb, you could have used a select instead of iterating over them all with an each.
3. For the Invoice.each_invoice, same comment I made on the other assignment. The method name is confusing. Looks like it's some kind of custom iterator, but really you are just displaying the invoice.
