### ISSUE TITLE
Movie Query app form - in class

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#33]
_This is assignment 32 and is due on Feb 17, 2015._

* Change your movie query app and add an HTML form to prompt the user for a movie title and submit to the controller/action you already have.
* You can still use the HTTP GET method in this case, because we want the old way of passing it in the request url to work.
* Use bootstrap to improve the look of the form.
* Refer to [Bootstrap form stylings](http://getbootstrap.com/css/#forms)
* Refer to [Rails form helpers](http://guides.rubyonrails.org/form_helpers.html)

**Comment by tgaeta** [comment]
@brianburridge https://github.com/tgaeta/Assignments/tree/master/movie_query

still needs more work on errors resulting from unknown movie titles, unlisted cast, and other odd-ball queries.

**Comment by brianburridge** [comment]
Looks really great. And yes to the error handling. I first tried the movie Kingsman and there was no cast so it crashed. But, that can come alter.

:+1:
