### ISSUE TITLE
Checkboxes for Many to Many

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#39]
_This is assignment 38 and is due on Feb 25, 2015._

* Note: This is a bonus assignment for those all caught up on homework.
* Using the app from 36 and 37, add checkboxes to a form for a many to many relationship.
* Review the [Railscast for this topic](http://railscasts.com/episodes/17-habtm-checkboxes-revised
)

**Comment by tgaeta** [comment]
@brianburridge 
https://secret-woodland-4108.herokuapp.com/
https://github.com/tgaeta/jboard

may need help identifying weird issue with the checkbox... adding and removing checkboxes works fine in the admin, works fine if you're removing some checkboxes, but if i have one checkbox left and try to unclick it, it won't save.

**Comment by brianburridge** [comment]
I guess you fixed the checkboxes since then? Working ok for me.

:+1:
