### ISSUE TITLE
Using ActiveAdmin for fully customizable, but quick, back-end admins

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#41]
_This is assignment 40 and is due on Feb 26, 2015._

* Add [ActiveAdmin](https://github.com/activeadmin/activeadmin) to your current application
* Review the [documentation](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md)
* Create an active admin resource for every model in your app
* Do some customization
* Ensure all forms save and allow the user to set the relationships
* Deploy to Heroku
* Paste the link to your Heroku app in a comment here for my review

**Comment by tgaeta** [comment]
@brianburridge 
https://secret-woodland-4108.herokuapp.com/admin

**Comment by brianburridge** [comment]
@tgaeta Editing Jobs, Applications and users throws an error.

**Comment by tgaeta** [comment]
@brianburridge - will take a look at it. Thanks.

**Comment by tgaeta** [comment]
@brianburridge - can you tell me where the error is occurring, specifically what you changed to throw the error? I just tried it on the admin and on the normal side on heroku, and everthing was updating without error.

**Comment by brianburridge** [comment]
Step 1: Go to /admin
Step 2: Click on Users
Step 3: Edit the only user there
Step 4: Click 'Update User'

Same with editing any Job.

Looks like Applicants is working though so forget I mentioned that one.

FYI: If you add a 'title' method to your Job model that returns the position and location appended together, ActiveAdmin will use that in the dropdown box for Job on your applicant form.

Also, your User, Technology, and Job resources for activeadmin don't have any permitted params, so they can't be edited or created.

**Comment by tgaeta** [comment]
@brianburridge Fixed all of the errros...

![Image of ActiveAdmin](http://i.imgur.com/RYxffsV.png)
... I got the job title, location, as well as the job id to diplay in the dropdown properly; however, I am getting a violation of the foreign key errors when I submit the job application. I've pushed it to heroku so you can see it and have also attached images.

![Image of ActiveAdmin Error](http://i.imgur.com/NBwCG3g.png)

I didn't think I was altering the tables by displaying the types for the form field. Any ideas?

Code:
```ruby
  form do |f|
    f.inputs do
      f.input :job, collection: Job.all.map { |job|
        [job.position + ' | ' + job.location + ' | ' +  job.id.to_s]
      }
      f.input :name
      f.input :user
      f.input :resume
      f.input :cover_letter
      f.input :image
      f.input :remote_image
      actions
    end
```

**Comment by tgaeta** [comment]
@brianburridge Your suggestion worked like a charm. Thank you.

**Comment by brianburridge** [comment]
:+1:
