### ISSUE TITLE
Build Pinterest

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#43]
_This is assignment 42 and is due on Mar 02, 2015._

* Should have these models: User, Pin, Board
* The home page should show "pins" from all users, and not in a table format but a grid
* Should use pagination with Kaminari on the pin page
* User should be able to create new pins, uploading an image to represent them.
* A Pin should have these attributes and belong to the user who added it: title, description, board, url, pin image
* A user should be able to create boards to pin items to. Every pin belongs to one board. A board has a name and belongs to a user.
* When the user clicks on a pin from the home page, it can either pop the pin up like Pinterest does, or go to a separate show page.
* There should be a search form to search the descriptions of the pins and show those matching (across all users).
* There should be a nav providing links to the home page, the user's pins, and the user's boards
* Bonus: make it look amazing!

**Comment by tgaeta** [comment]
@brianburridge https://stark-brushlands-7818.herokuapp.com/

Search feature still needs love; need to work on the 're-pinning' from the main view

**Comment by brianburridge** [comment]
@tgaeta really, repinning wasn't even part of this assignment. Just adding pins was. Feel free to try and get it finished, but that shouldn't hold you up from submitting this assignment.

**Comment by tgaeta** [comment]
@brianburridge - update - only one thing left on this assignment before i hit the complete button. i need to create a user pins page and link to it from the navbar... sorta metally checked out yesterday because i was burnt out - went for an hour long walk but didn't seem to help - i'll tackle this after class and knock out last night's rake tasks hw as well - https://stark-brushlands-7818.herokuapp.com

**Comment by tgaeta** [comment]
@brianburridge 
https://stark-brushlands-7818.herokuapp.com/
https://github.com/tgaeta/pinterest

**Comment by brianburridge** [comment]
:+1:
