### ISSUE TITLE
Restricting ActiveAdmin access

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#45]
_This is assignment 44 and is due on Mar 05, 2015._

* Adjust your Pinterest app to only allow "admin" users to access the /admin section

**Comment by tgaeta** [comment]
@brianburridge done; however, i did set the current_user as admin. I also set my drop navigation to render the admin button if the user is an admin, and an upload pin if just a normal user.

https://stark-brushlands-7818.herokuapp.com

**Comment by brianburridge** [comment]
:+1:
