### ISSUE TITLE
Debugging a Rails Application

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#49]
_This is assignment 48 and is due on Mar 11, 2015._

* Read about ri [Up and Running With Ruby Interactive](http://samuelmullen.com/2012/01/up-and-running-with-ruby-interactive-ri/), [5 Reasons You Should Use ri To Read Ruby Documentation](http://www.jstorimer.com/blogs/workingwithcode/7766081-5-reasons-you-should-use-ri-to-read-ruby-documentation)
* Try [Dash](http://kapeli.com/dash)
* Try [OmniRef](https://www.omniref.com/)
* Sign up to use the [Suncoast Dev Slack](http://suncoast.io)
* Install the [better_errors gem](https://github.com/charliesome/better_errors) in your Pinterest application. Create an error to see how it works.
* Read about the [Rails logger](http://guides.rubyonrails.org/debugging_rails_applications.html) and implement some lines in your controller. Output an instance variable using the `.inspect` method to the log. Paste the section of your log file in a comment in this issue. In an issue comment direct me to where you have added the logger statements. (Yes, in this case you can check logger statements in).
* Read about using the [pry console debugger](https://github.com/nixme/pry-debugger) and try it in a controller action.

**Comment by tgaeta** [comment]
boards_controller.rb
```ruby
def create
    @user = User.find(params[:user_id])
    @board = @user.boards.new(board_params)
    Rails.logger.debug puts "New board: #{@board.inspect}"
    respond_to do |format|
      if @board.save
        format.html do
          redirect_to [@board.user, @board],
                      notice: 'Board successfully created.'
        end
      else
        format.html { render :new }
      end
    end
  end
```

Log Output:
```
Started POST "/users/1300/boards" for 127.0.0.1 at 2015-03-10 22:07:22 -0400
Processing by BoardsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"tfFSTeXKe9/hXY+a//FZBln+qbW/QtnGVmUydO/B5cGk5FOqFVFRbqPuRKvbYFKvtcD8tIo52OrXINDLSyXR6w==", "board"=>{"name"=>"Another Test", "user_id"=>"1300"}, "commit"=>"Create Board", "user_id"=>"1300"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = $1 LIMIT 1  [["name", "Guest"]]
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1300]]
New board: #<Board id: nil, name: "Another Test", user_id: 1300, created_at: nil, updated_at: nil>
   (0.3ms)  BEGIN
  SQL (1.0ms)  INSERT INTO "boards" ("user_id", "name", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["user_id", 1300], ["name", "Another Test"], ["created_at", "2015-03-11 02:07:22.600537"], ["updated_at", "2015-03-11 02:07:22.600537"]]
   (1.6ms)  COMMIT
Redirected to http://localhost:3000/users/1300/boards/15472
Completed 302 Found in 11ms (ActiveRecord: 3.7ms)
```

**Comment by brianburridge** [comment]
:+1:
