### ISSUE TITLE
Sending Email

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#57]
_This is assignment 55 and is due on Mar 24, 2015._

* Read the Rails guide on [Action Mailer](http://guides.rubyonrails.org/action_mailer_basics.html)
* Add a welcome mailer to the sign up process in your Pinterest app
* Get it working on your laptop first, using the [letter_opener gem](https://github.com/ryanb/letter_opener)
https://devcenter.heroku.com/articles/sendgrid#ruby-rails
* Next, deploy to Heroku and setup with sendgrid
* Ensure emails are being received by users when signing up on Heroku

**Comment by tgaeta** [comment]
@brianburridge 

https://stark-brushlands-7818.herokuapp.com/

![image](http://i.imgur.com/DvzXyRs.png)

https://github.com/tgaeta/pinterest/blob/78f5e2f72f0f1a54b30f3bb35f9e9037f7f6921f/config/environments/production.rb

**Comment by tgaeta** [comment]
When you're done viewing the image - go here to delete it please: http://imgur.com/delete/KUeevHLNXBLrwnC

**Comment by brianburridge** [comment]
I signed up and got the email in my inbox. :+1:
