### ISSUE TITLE
CoffeeScript

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#61]
_This is assignment 60 and is due on Mar 30, 2015._

* Review the Rails guide on [Working with JavaScript in Rails](http://guides.rubyonrails.org/working_with_javascript_in_rails.html)
* Refer to the [CoffeeScript docs](http://coffeescript.org/)
* Write some CoffeeScript in your Pinterest app to listen for a click on the header/logo of your app (in the nav), and when clicked, popup a bootstrap modal with some about information for your app.
* Bonus: Use Ajax in one place in your Pinterest app (deleting an item, adding an item, etc)

**Comment by tgaeta** [comment]
@brianburridge: https://stark-brushlands-7818.herokuapp.com/ 

app/assets/javascripts/pins.coffee:
```coffeescript
$(document).on 'page:change', ->
  $('.brand').click ->
    $('#brandModal').modal 'show'
```

app/views/pins/index.html.erb:
```erb
<div class="modal fade" id="brandModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">About Pinterested</h4>
      </div>
      <div class="modal-body">
        Pinterested was built by <%= link_to 'Tony Gaeta', 'http://www.tonygaeta.com' %> during his time at The Iron Yard.
      </div>
    </div>
  </div>
</div>
```

**Comment by brianburridge** [comment]
:+1:
