### ISSUE TITLE
Creating Variables and Literals

### ISSUE THREAD

**Issue by brianburridge** [tgaeta/Assignments#7]
_This assignment is due on Jan 28, 2015._

* Create code for each comment in [this gist](https://gist.github.com/brianburridge/79de494772daf7976ea9)
* Run the code and paste the output into your issue as a comment for this assignment
* It should list all the proper class names and all class tests should result in 'true'
* Before you run it, can you guess what will happen with the constant code you've created?

**Comment by tgaeta** [comment]
Tonys-MacBook-Pro:TheIronYard Tony_MBP$ ruby variables\&constants.rb 
String
Date
Fixnum
Array
Array
Hash
true
true
true
true
true
true
String
Fixnum
Array
Hash
Symbol
variables&constants.rb:42: warning: already initialized constant LAST_NAME
variables&constants.rb:40: warning: previous definition of LAST_NAME was here
Davidson
